=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/inventory.dtd
<!ELEMENT inventory (commentary?, sense+, WORD_META)>
<!ATTLIST inventory lemma CDATA #REQUIRED>

<!-- 
  the inventory's lemma attribute should take the form: word_stem-[nva] 
-->

<!ELEMENT commentary (#PCDATA)>

<!-- 
(optional) unstructured commentary to be seen by the annotators.  Can be at the word-level
or at the sense-level.  Can include things like:  a long technical definition, explicit
guidance on distinguishing close senses, verb-frames, etc.
-->

<!ELEMENT sense (commentary?, examples, mappings, SENSE_META)>
<!ATTLIST sense 
  n CDATA #REQUIRED
  type CDATA #IMPLIED     
  name CDATA #REQUIRED
  group CDATA #REQUIRED>

<!--
  id = the number ID of the sense
  type = the type of the sense (e.g. concrete, abstract, technical, archaic, event)
  name = a clear and concise description of the sense (for the annotators)
  group = A group identifier: this allows very coarse clustering of the senses.
         used, for example, distinguish homographs (fan the blows air vs. football fan)
         and to cluster closely related senses (e.g. school as building & school as process
         vs. school of fish)
         
-->

<!ELEMENT examples (#PCDATA)>

<!--
  examples that illustrate which common patterns of usage fall under this sense.
  should include helpful boundary cases and idiomatic expressions.
  NOTE: each example should be separated by a newline character.
-->

<!ELEMENT mappings (gr_sense?,wn+,omega,pb,vn?,fn?)>
<!ELEMENT wn (#PCDATA)>

<!--
  a space/comma delimited list of the wordnet sense-numbers which fit under this sense, or "-"
  if none do.
-->

<!ATTLIST wn 
 version CDATA #REQUIRED
 lemma CDATA #IMPLIED>

<!ELEMENT gr_sense (#PCDATA)>

<!--
 version = WordNet Version
 lemma = WordNet lemma (e.g. raise, raise_up, raise_hell) 
-->

<!ELEMENT omega (#PCDATA)>
<!ELEMENT pb (#PCDATA)>
<!ELEMENT vn (#PCDATA)>
<!ELEMENT fn (#PCDATA)>
<!-- additional mapping elements can be added as the need arises -->

<!ELEMENT SENSE_META EMPTY>
<!ATTLIST SENSE_META clarity CDATA #IMPLIED>
<!-- 
  a measure of the sense's clarity (should be a numerical score between 0 
  and 1.  This should not be edited by hand - it will be automatically generated.
-->
  
<!ELEMENT WORD_META EMPTY>
<!ATTLIST WORD_META 
  authors CDATA #REQUIRED  
  sample_score CDATA #IMPLIED>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/clamp-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="clamp-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="Fasten or fix something to itself or something else." type="">  
        <commentary>
            Note: May be abstract.
        </commentary>
        <examples>
            Clamp the chair together until the glue has hardened.
            John clamped his finger to the board.
            The military clamped a curfew on the populace. 
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,2</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>clamp.01</pb>
            <vn>tape-22.4-1</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="CLAMP DOWN: repress or suppress (something
         regarded as undesireable); deny expression to." type="">
        <commentary>
            Is: CLAMP DOWN
        </commentary>
        <examples>
            The police clamped down on illegal drugs. 
            We have to clamp down on gang elements in the city. 
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0"></wn>
            <wn lemma="clamp_down" version="3.0">1</wn>
            <omega></omega><pb>NM</pb>
            <vn>NM</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="3" name="CLAMP DOWN: physically bite." type="">
        <commentary>
            Is: CLAMP DOWN 
        </commentary>
        <examples>
            The dog really clamped down.
            I had to clamp down to keep from screaming out in pain. 
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0"></wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NM</pb>
            <vn>NM</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="4" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>
     

<ita count="11" ann_1_2_agreement="1.0" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/defer-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="defer-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="hold back to a later time" type="">
        <commentary>
        </commentary>
        <examples>
            She deferred her entrance to the university for a year.
            The company is offering to defer finance charges for the first year.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>defer.01</pb>
            <vn>NM</vn><fn>Change_event_time</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="yield to another's wish or opinion" type="">
        <commentary>
        </commentary>
        <examples>
            I defer to your greater wisdom.
            Must health policy for the uninsured defer to current anti-government sentiment?
            Why would the winner of a footbal coin toss defer to the loser?
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">2</wn>
            <omega></omega><pb>defer.02</pb>
            <vn>acquiesce-95</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="brownsw,greenlm" sample_score="-"/>

<ita count="24" ann_1_2_agreement="0.791666666667" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/bully-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="bully-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="Discourage or frighten with threats or a
   domineering manner; intimidate; be bossy towards someone." type="">  
        <commentary>
        </commentary>
        <examples>
            Her big brother always bullied her when she was young.
            Don't bully your classmates!
            It's hard not to bully other students when arguing in class.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,2</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>bully.01</pb>
            <vn>captain-29.8-1,force-59-1</vn><fn>Manipulate_into_doing</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="BULLY OFF: start a game by face-off." type="">
        <commentary>
            Is: BULLY OFF
        </commentary>
        <examples>
            The two teams bullied off.
            Bully off with your opponent.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0"></wn>
            <wn lemma="bully_off" version="3.0">1</wn>
            <omega></omega><pb>NM</pb>
            <vn>NM</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>
     

<ita count="11" ann_1_2_agreement="0.727272727273" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/accord-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="accord-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="Go together; fulfill the characteristics of." type="">  
        <commentary>
            Syntax Is: NP1[cotheme] ACCORD (PP{P NP[cotheme]}) 
        </commentary>
        <examples>
            All proceedings accorded with the stated mission of the organization.
            Our ideas accorded and the meeting was adjourned.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NM</pb>
            <vn>NP</vn><fn>Compatability</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="Allow to have; assign." type="">
        <commentary>
            Syntax Includes: NP1[agent] ACCORD NP2[patient]
            NP1[agent] ACCORD NP2[recipient] 
        </commentary>
        <examples>
            The government accorded full rights and privileges to the new
            citizens.
            The FDA accords the label to drugs believed effective but previously
            untested.
            The company accords new employees the best health coverage in the industry.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">2</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>accord.01</pb>
            <vn>NP</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>
     

<ita count="4" ann_1_2_agreement="0.75" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/ditch-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="ditch-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="forsake, sever ties with" type="">  
        <commentary>
        </commentary>
        <examples>
            The British say that he ditched his plane in the Atlantic.
            The company ditched her in no time flat.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,3</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NP</pb>
            <vn>NP</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="throw away" type="">
        <commentary>
        </commentary>
        <examples>
            Buergel ditched his notes, saying he'd rather respond to the
            previous speakers.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">2</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NP</pb>
            <vn>NP</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="3" name="crash, crash-land" type="">
        <commentary>
        </commentary>
        <examples>
            The plane ditched in 3600 feet of shark-infested ocean.
            I ditched my car after it spun out.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">4,5</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NP</pb>
            <vn>NP</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="4" name="cut a trench in" type="">
        <commentary>
        </commentary>
        <examples>
            Soon after, he fenced and ditched the land and
            built a granary and a stable thereon.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">6</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NP</pb>
            <vn>NP</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="5" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="greenlm" sample_score="-"/>
     
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/scant-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="scant-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="spare in quality or quantity" type="">  
        <commentary>
        </commentary>
        <examples>
            Our leisure time is scanted by this demanding job.
            Scant must be your takings.
            We had to scant the older children in order to nourish the newborn.
            In the perilous computer market, competition is fierce and profits scant.
            These three writers scanted the middle ground of human intercourse.
            Reforms generally scant the difference between exchange-rate arrangements.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,2,3</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>scant.01</pb>
            <vn>NP</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <WORD_META authors="conger" sample_score="-"/>
     

<ita count="2" ann_1_2_agreement="1.0" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/jumble-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="jumble-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="Be mixed (up) together." type="">  
        <commentary>
            Syntax Is: NP1[theme] JUMBLE
        </commentary>
        <examples>
            His words jumbled.
            The marbles jumbled as they settled. 
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>jumble.01</pb>
            <vn>NM</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="Assemble without order or sense." type="">
        <commentary>
            Syntax Is: NP1[cause] JUMBLE NP2[theme]  
        </commentary>
        <examples>
            She jumbles the words when she writes.
            He jumbled the tickets when he dropped the pile.  
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">2,3</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>jumble.01</pb>
            <vn>shake-22.3-2</vn><fn>Cause_to_amalgamate</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>
     

<ita count="6" ann_1_2_agreement="0.666666666667" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/rinse-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="rinse-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="wash off, clean" type="">  
        <commentary>
            Includes: RINSE OFF
            Syntax Is:  NP1[agent] RINSE (off) NP2[patient] (PP)
        </commentary>
        <examples>
            Rudy rinsed off his hands.
            Remember to wash and rinse the dish with soap.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,2</wn>   
            <wn lemma="rinse_off" version="3.0">1</wn>
            <omega></omega><pb>NP</pb>
            <vn>braid-41.2.2,wipe_manner-10.4.1-1</vn><fn>Removing</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="rinse one's mouth with mouthwash, gargle" type="">
        <commentary>
            Syntax Is: NP1[agent] RINSE NP2[patient]
        </commentary>
        <examples>
            When I got home, I rinsed my mouth with the antiseptic mouthwash.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">3</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NP</pb>
            <vn>braid-41.2.2</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="greenlm" sample_score="-"/>
     

<ita count="3" ann_1_2_agreement="1.0" />
</inventory>
