=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/inventory.dtd
<!ELEMENT inventory (commentary?, sense+, WORD_META)>
<!ATTLIST inventory lemma CDATA #REQUIRED>

<!-- 
  the inventory's lemma attribute should take the form: word_stem-[nva] 
-->

<!ELEMENT commentary (#PCDATA)>

<!-- 
(optional) unstructured commentary to be seen by the annotators.  Can be at the word-level
or at the sense-level.  Can include things like:  a long technical definition, explicit
guidance on distinguishing close senses, verb-frames, etc.
-->

<!ELEMENT sense (commentary?, examples, mappings, SENSE_META)>
<!ATTLIST sense 
  n CDATA #REQUIRED
  type CDATA #IMPLIED     
  name CDATA #REQUIRED
  group CDATA #REQUIRED>

<!--
  id = the number ID of the sense
  type = the type of the sense (e.g. concrete, abstract, technical, archaic, event)
  name = a clear and concise description of the sense (for the annotators)
  group = A group identifier: this allows very coarse clustering of the senses.
         used, for example, distinguish homographs (fan the blows air vs. football fan)
         and to cluster closely related senses (e.g. school as building & school as process
         vs. school of fish)
         
-->

<!ELEMENT examples (#PCDATA)>

<!--
  examples that illustrate which common patterns of usage fall under this sense.
  should include helpful boundary cases and idiomatic expressions.
  NOTE: each example should be separated by a newline character.
-->

<!ELEMENT mappings (gr_sense?,wn+,omega,pb,vn?,fn?)>
<!ELEMENT wn (#PCDATA)>

<!--
  a space/comma delimited list of the wordnet sense-numbers which fit under this sense, or "-"
  if none do.
-->

<!ATTLIST wn 
 version CDATA #REQUIRED
 lemma CDATA #IMPLIED>

<!ELEMENT gr_sense (#PCDATA)>

<!--
 version = WordNet Version
 lemma = WordNet lemma (e.g. raise, raise_up, raise_hell) 
-->

<!ELEMENT omega (#PCDATA)>
<!ELEMENT pb (#PCDATA)>
<!ELEMENT vn (#PCDATA)>
<!ELEMENT fn (#PCDATA)>
<!-- additional mapping elements can be added as the need arises -->

<!ELEMENT SENSE_META EMPTY>
<!ATTLIST SENSE_META clarity CDATA #IMPLIED>
<!-- 
  a measure of the sense's clarity (should be a numerical score between 0 
  and 1.  This should not be edited by hand - it will be automatically generated.
-->
  
<!ELEMENT WORD_META EMPTY>
<!ATTLIST WORD_META 
  authors CDATA #REQUIRED  
  sample_score CDATA #IMPLIED>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/arm-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="arm-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="equip, provide with weapons" type="">  
        <commentary>
            Sytnax Is:  NP1[agent] ARM NP2[recipient] (PP[patient[weapon]])
            Note: NP2 recipient may be reflexive
        </commentary>
        <examples>
            She armed the others and told them to stand by.
            He said it was time we armed the National Guard on the border patrol with real bullets.
            They armed themselves with bows and spears, snatching guns when they could. 
            They have armed themselves with a long-term strategy for running their finances.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">1,2</wn>   
            <wn lemma="" version=""/>
            <omega/>
            <pb>arm.01</pb>
            <vn>equip-13.4.2-1</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="activate, make ready" type="">
        <commentary>
            NP1[agent] ARM NP2[theme[inanimate]]
        </commentary>
        <examples>
            About that time, we armed the automatic system.
            He armed the BFGs and pointed them at the cottage.
            She armed the door and sat down on her jumpseat opposite my row.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version=""/>
            <wn lemma="" version=""/>
            <omega/>
            <pb>arm.01</pb>
            <vn>NM</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="duffielc,greenlm" sample_score="-"/>
     

<ita count="16" ann_1_2_agreement="1.0" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/portray-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="portray-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="describe or depict someone or something" type="">
        <commentary>
        </commentary>
        <examples>
            The book portrays the actor as a selfish person.
            The father is portrayed as a good-looking man in this painting.
            Sophocles allegedly said that he portrayed his characters as they ought to be, Euripides as they are.
            It accurately portrayed what I have experienced as a Brown oarsman.
            I found out that the movie accurately portrayed what actually happened that year.
            Does the Flight Simulator accurately portray how to handle a C172?
            Next to the angel the painter portrayed a cherub with the palm frond.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">1,2,4</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb>portray.01</pb>
            <vn>characterize-29.2-1-1</vn><fn>Communicate_categorization</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="enact, play the role of" type="">
        <commentary>
        </commentary>
        <examples>
            The actor portrays an elderly, lonely man.
            The core acting company member will portray the scheming blackmailer Krogstad.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">3</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb/>
            <vn/>
            <fn/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="duffielc,brownsw" sample_score="-"/>

<ita count="35" ann_1_2_agreement="0.742857142857" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/shape-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="shape-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="form or make something" type="">
        <commentary>
            The shaper has complete control over the final shape.
        </commentary>
        <examples>
            She shaped the dough into balls.
            The child shaped the clay.
            Learn to shape dim sum from a master.
            She shapes a rotund jar with a short, narrow lip.
            She shapes elliptical short stories into torched songs of uplifting pessimism.
        </examples>
        <mappings>
            <wn version="3.0">2,3</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb>shape.01</pb>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
    <sense group="1" n="2" name="influence, give direction" type="">
        <commentary>
            The shaper could be only one factor influencing the final shape.
        </commentary>
        <examples>
            She was shaped by a mother who bound her to excellence.
            Anne was shaped by her political mentors.
            It is clear he was shaped by his early environment.
            The media's primary objective is to shape public opinion.
        </examples>
        <mappings>
            <wn version="3.0">1</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb>shape.01</pb>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
    <sense group="1" n="3" name="act, form, or progress according to a plan or ideal" type="">
        <commentary>
            includes SHAPE UP
        </commentary>
        <examples>
            Plans are shaping up nicely.
            Shape up your brows; it's the easiest way to transform your look!
            The men's-only fitness center helps shy guys shape up.
            Shape up or ship out!
        </examples>
        <mappings>
            <wn version=""/>
            <wn lemma="shape_up" version="3.0">1</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
<sense group="1" n="4" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="vieweg,duffielc,brownsw" sample_score="-"/>

<ita count="37" ann_1_2_agreement="0.810810810811" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/spread-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="spread-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="(cause to) open to full extent or width" type="">
        <commentary>
            Syntax is: NP1 SPREAD NP2
            Includes: SPREAD OUT
        </commentary>
        <examples>
            He spread his arms wider and gave her a devilish grin.
            The bird spread its wings, as it swooped down on a dead tree near a billboard.
            Orsyn spread the map out so all could see.
            Then slowly, once again, the pianist spread his fingers onto the keys.
            These birds can spread out their toes.
            We spread the picnic rug out on the ground and sat down to eat.
        </examples>
        <mappings>
            <wn version="3.0">4</wn>
            <wn lemma="spread_out" version="3.0">5,7</wn>
            <omega/>
            <pb>spread.03</pb>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="distribute or disseminate; be widespread" type="">
        <commentary>
            Includes: SPREAD OUT, SPREAD OVER
        </commentary>
        <examples>
            She spread butter and jam on the bread.
            Dr. Khronos has been spreading the information about his Vital Energy tapes.
            Spread out the seed and dry thoroughly before placing in a storage container.
            I use a small paint brush to spread varnish over the coil windings.
            The redundancies are spread across the clothing, banking and building industries.
            If we spread the work between us, it won't be so bad.
            They went back to the great hall, and a feast was spread for the king.
            We spread the bicycle parts out on the floor.
            The houses were spread out in a long row.
            A big oil spot spread across the water.
            Spread the news to your friends!
            Rumor and truth spread like wildfire when it came to his antics and sexual adventures.
            The fire ants had spread across the South, causing panic among local populations.
            Group members took signs, lit candles, and spread out along the street.
            The AIDS virus is spread through contact with blood and other body fluids.
            The suburbs spread out for miles to either side of the city.
        </examples>
        <mappings>
            <wn version="3.0">1,2,3,5,6,7,8,10</wn>
            <wn lemma="spread_out" version="3.0">1,2,3,4,6</wn>
            <wn lemma="spread_over" version="3.0">1</wn>
            <omega/>
            <pb>spread.01,spread.02</pb>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="3" name="cover" type="">
        <commentary>
            Note: Must include a 'with' PP specifying the cover or spread.
            Syntax is: NP1[agent] SPREAD NP2 with NP3
        </commentary>
        <examples>
            He spread the bread with cheese. (NOTE: compare to example in sense 2)
            Taking a cue from one of their father's sermons, they spread the ground with ash.
            Exhibition openings are often potluck parties where artists spread the table with homemade favorites.
            Eurynome and the nurse spread the bed with soft coverlets.
        </examples>
        <mappings>
            <wn version="3.0">9</wn>
            <omega/>
            <pb>spread.01</pb>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
<sense group="1" n="4" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="duffielc,hwangd,brownsw" sample_score="-"/>

<ita count="149" ann_1_2_agreement="0.906040268456" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/flourish-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="flourish-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="Thrive physically, psychologically, or in
   one's career; prosper or grow." type="">  
        <commentary>
        </commentary>
        <examples>
            The deer population in this town is thriving.
            Business is flourishing.
            Pikaia flourished at the same time as the Burgess fauna.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,2</wn>   
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>flourish.01</pb>
            <vn>exist-47.1-1,gorge-39.6</vn><fn>Thriving</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="Brandish, usually a firearm." type="">
        <commentary>
        </commentary>
        <examples>
            She flourished her gun for all to see.
            It was better to go to the next town to flourish the pistol.
            It's not like we go around Iraq flourishing ICBMs. 
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">3</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb>NM</pb>
            <vn>NM</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>
     

<ita count="12" ann_1_2_agreement="0.916666666667" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/bias-n.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="bias-n">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="A partiality that prevents objective consideration of an issue or situation." type="">
        <commentary>
            BIAS[+abstract]
        </commentary>
        <examples>
            She has a bias concerning her efficiency as a worker.
            We cannot approach the law with bias.
        </examples>
        <mappings>
            <wn version="3.0">1</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="A line or cut across a fabric that is not at right angles to a side of the fabric." type="">
        <commentary>
            BIAS[+concrete]
        </commentary>
        <examples>
            The fabric was cut along a bias.
        </examples>
        <mappings>
            <wn version="3.0">2</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>

<ita count="24" ann_1_2_agreement="0.833333333333" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/innovation-n.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="innovation-n">
    <commentary>
    </commentary>
    
    <sense group="1" n="1" name="something new" type="Abstraction">
        <commentary>
            A new device or process resulting from study, experimentation, or insight; a new creation.
        </commentary>
        <examples>
            New innovations in medicine will allow you to live longer.
            I've created an innovation!
            Shop for the latest in technology innovations.
            When the Heimlich Maneuver was first invented, it was an innovation in health care.
            John's process for reducing chip size won the &quot;Innovation of the Year&quot; award.
        </examples>
        <mappings>
            <wn version="2.0">
                1
            </wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
    <sense group="1" n="2" name="inventing or starting" type="Event">
        <commentary>
            INNOVATION[+event]
            The act of inventing or beginning something new.
        </commentary>
        <examples>
            We encourage the innovation of new techniques and technologies.
            The innovation of the printing press allowed ideas to spread across Europe.
            Our company is committed to innovation.
            Innovation will always keep the technology industry from stagnating.
        </examples>
        <mappings>
            <wn version="2.0">
                2 3
            </wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="hertlerb" sample_score="-"/>

<ita count="33" ann_1_2_agreement="0.909090909091" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/impress-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="impress-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="have an emotional or cognitive impact on" type="">
        <commentary>
        </commentary>
        <examples>
            The child impressed me as unusually mature.
            Her masterful control of the bow impressed the audience.
            My mother impressed on us kids the importance good hygene.
        </examples>
        <mappings>
            <wn version="3.0">1,2,3</wn>
            <wn lemma="" version="3.0"/>
            <omega/>
            <pb>impress.01,impress.02</pb>
            <vn>amuse-31.1</vn><fn>Experiencer_obj</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="imprint" type="">
        <commentary>
        </commentary>
        <examples>
            To make a batik, you impress a design with wax.
            Typing or otherwise impressing printing on one side of the envelope causes corresponding marks on the message section.
            For the color to take form and impress itself on the stuff, some additional component is needed.
        </examples>
        <mappings>
            <wn version="3.0">4,5,7</wn>
            <omega/>
            <pb>NM</pb>
            <vn>NM</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="3" name="conscript; force into service" type="">
        <commentary>
        </commentary>
        <examples>
            The Royal Navy also impressed seamen from inbound British merchant ships at sea.
        </examples>
        <mappings>
            <wn version="3.0">6</wn>
            <omega/>
            <pb>NM</pb>
            <vn>NM</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="4" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="brownsw,greenlm" sample_score="-"/>

<ita count="30" ann_1_2_agreement="0.933333333333" />
</inventory>
