=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/inventory.dtd
<!ELEMENT inventory (commentary?, sense+, WORD_META)>
<!ATTLIST inventory lemma CDATA #REQUIRED>

<!-- 
  the inventory's lemma attribute should take the form: word_stem-[nva] 
-->

<!ELEMENT commentary (#PCDATA)>

<!-- 
(optional) unstructured commentary to be seen by the annotators.  Can be at the word-level
or at the sense-level.  Can include things like:  a long technical definition, explicit
guidance on distinguishing close senses, verb-frames, etc.
-->

<!ELEMENT sense (commentary?, examples, mappings, SENSE_META)>
<!ATTLIST sense 
  n CDATA #REQUIRED
  type CDATA #IMPLIED     
  name CDATA #REQUIRED
  group CDATA #REQUIRED>

<!--
  id = the number ID of the sense
  type = the type of the sense (e.g. concrete, abstract, technical, archaic, event)
  name = a clear and concise description of the sense (for the annotators)
  group = A group identifier: this allows very coarse clustering of the senses.
         used, for example, distinguish homographs (fan the blows air vs. football fan)
         and to cluster closely related senses (e.g. school as building & school as process
         vs. school of fish)
         
-->

<!ELEMENT examples (#PCDATA)>

<!--
  examples that illustrate which common patterns of usage fall under this sense.
  should include helpful boundary cases and idiomatic expressions.
  NOTE: each example should be separated by a newline character.
-->

<!ELEMENT mappings (gr_sense?,wn+,omega,pb,vn?,fn?)>
<!ELEMENT wn (#PCDATA)>

<!--
  a space/comma delimited list of the wordnet sense-numbers which fit under this sense, or "-"
  if none do.
-->

<!ATTLIST wn 
 version CDATA #REQUIRED
 lemma CDATA #IMPLIED>

<!ELEMENT gr_sense (#PCDATA)>

<!--
 version = WordNet Version
 lemma = WordNet lemma (e.g. raise, raise_up, raise_hell) 
-->

<!ELEMENT omega (#PCDATA)>
<!ELEMENT pb (#PCDATA)>
<!ELEMENT vn (#PCDATA)>
<!ELEMENT fn (#PCDATA)>
<!-- additional mapping elements can be added as the need arises -->

<!ELEMENT SENSE_META EMPTY>
<!ATTLIST SENSE_META clarity CDATA #IMPLIED>
<!-- 
  a measure of the sense's clarity (should be a numerical score between 0 
  and 1.  This should not be edited by hand - it will be automatically generated.
-->
  
<!ELEMENT WORD_META EMPTY>
<!ATTLIST WORD_META 
  authors CDATA #REQUIRED  
  sample_score CDATA #IMPLIED>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/correct-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="correct-v">    
    <commentary>
        Contains duplicate WN mappings.
    </commentary>
    <sense group="1" n="1" name="rectify, remedy, remove mistakes or errors" type="">  
        <commentary>
            Syntax Is:
            NP1 CORRECT NP2[topic]
        </commentary>
        <examples>
            Students said it was helpful if the teacher corrected their pronunciation.
            How do you correct the wrongs done to victims of the Holocaust?
            Correct the alignment of the front wheels.
            These glasses hopefully will correct his myopia.
            I bought a chair to help me correct by posture.
            You need to correct your attitude, young man.
        </examples>
        <mappings>
            <wn version="3.0">1,2,4,7,8</wn>
            <omega/>
            <pb>correct.01</pb>
            <vn>NM</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="grade or mark" type="">
        <commentary>
        </commentary>
        <examples>
            I've got thirty exam papers to correct.
            The homework will be corrected, graded, and returned as soon as possible.
            I spent all night correcting your quizzes.
        </examples>
        <mappings>
            <wn version="3.0">7</wn>
            <omega/>
            <pb>NM</pb>
            <vn>other_cos-45.4</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="3" name="punish, scold or discipline" type="">
        <commentary>
            Syntax Is:
            NP1[agent] CORRECT NP2[patient]
        </commentary>
        <examples>
            He was severely corrected by his superiors for the mistake.
            She corrected him for his insesitive remarks by grounding him for a week.
            The teacher corrects his students rather frequently.
        </examples>
        <mappings>
            <wn version="3.0">3,5</wn>
            <omega/>
            <pb>correct.01</pb>
            <vn>NM</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="4" name="go down in value" type="">
        <commentary>
            NOTE: This sense only used for frames of stock and money/prices.
        </commentary>
        <examples>
            The stock market corrected last week.
            Prices have corrected all throughout the nation.
        </examples>
        <mappings>
            <wn version="3.0">6</wn>
            <omega/>
            <pb>NM</pb>
            <vn>NM</vn><fn>NP</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="5" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="hwangd, vieweg,duffielc" sample_score="-"/>
     

<ita count="34" ann_1_2_agreement="0.882352941176" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/infect-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="infect-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="contaminate with a disease or other malicious quality" type="">  
        <commentary>
        </commentary>
        <examples>
            How bad debt infected the world.
            Hackers infected the legitimate website with a malicious script.
            People who were infected with the T virus became zombies.
            The earlier the baby is infected, the more severe the effects.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">1,2,3</wn>   
            <wn lemma="" version=""/>
            <omega/>
            <pb>infect.01</pb>
            <vn>fill-9.8</vn><fn/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="cause a feeling or action" type="">
        <commentary>
        </commentary>
        <examples>
            The teacher always infects everyone with her happiness.
            Something in her terrible agitation infected him strangely.
            Mahan infected the group with a zeal for creative education.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">4</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb/>
            <vn/>
            <fn/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="clarklm" sample_score="-"/>
     

<ita count="19" ann_1_2_agreement="1.0" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/telescope-n.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="telescope-n">
    <commentary>
        monosemous
    </commentary>
    
    <sense group="1" n="1" name="an instrument, usually optical,  that magnifies distant objects" type="">
        <commentary>
            TELESCOPE[+artifact][+instrument][+imager][+receptor][+of_wavelength][+electromagnetic][+of_objects][+distant]
        </commentary>
        <examples>
            These data were obtained with radio telescopes.
            John bought his children a refractor telescope to look at the moon with.
        </examples>
        <mappings>
            <wn version="3.0">1</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
    
    <WORD_META authors="ahouston" sample_score="-"/>
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/sieve-v.xml
<?xml version="1.0" ?>
<!DOCTYPE inventory SYSTEM "inventory.dtd">
<inventory lemma="sieve-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="Distinguish, sort, or separate out." type="">  
        <commentary>
            Includes: SIEVE OUT
            Note: May be metaphorical 
        </commentary>
        <examples>
            The company sieved the job applicants.
            Sieve out those samples from the bad ones.
            The customer sieved through the selection.
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">1,2,4</wn>   
            <wn lemma="sieve_out" version="3.0">1</wn>
            <omega></omega><pb></pb>
            <vn></vn><fn></fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="Separate by passing through a straining device." type="">
        <commentary>
        </commentary>
        <examples>
            Sieve the flour before mixing.
            We should sieve the mud from the dig site.  
        </examples>
        <mappings>
            <gr_sense></gr_sense>
            <wn version="3.0">3</wn>
            <wn lemma="" version="3.0"></wn>
            <omega></omega><pb></pb>
            <vn></vn><fn></fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="corvey" sample_score="-"/>
     

<ita count="4" ann_1_2_agreement="0.75" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/vacate-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="vacate-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="leave or give up a job, post, or tenancy" type="">
        <commentary>
        </commentary>
        <examples>
            Algerian gunmen vacated the flow station yesterday morning, releasing close 
            to 40 Agip staff, soldiers and naval personnel.
            He vacated the office of sheriff in 1999.
            In 2003 he vacated the British Super Middlweight title.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">1,2</wn>
            <wn lemma="" version="3.0"/>
            <omega/>
            <pb>vacate.01</pb>
            <vn>escape-51.1,resign-10.11</vn><fn>Quitting_a_place,Departing</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="annul, make legally void" type="">
        <commentary>
        </commentary>
        <examples>
            SciMed Life Systems Inc. said a federal appeals court vacated an earlier 
            summary judgment in its favor. 
            The judge vacated the sentence.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">3</wn>
            <omega/>
            <pb>vacate.01</pb>
            <vn>NM</vn><fn>NM</fn>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="brownsw,greenlm" sample_score="-"/>

<ita count="16" ann_1_2_agreement="0.9375" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/ontonotes/sense-inventories/trap-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="trap-v">
    <commentary>
    </commentary>
    <sense group="1" n="1" name="place in a confining or embarassing position" type="">
        <commentary>
            Note: compare to sense 2. This sense is only metaphorical.
        </commentary>
        <examples>
            Deflation has trapped the Federal Reserve into a scenario that will depress the economy.
            The embargo trapped the country in a vice between ruthless insurgents and unloved occupiers.
            Japan had complete miliary control so Korea was trapped in a hopeless situation.
            Are you trapped in procrastination by your decision-making ability?
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">1</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb>trap.01</pb>
            <vn>force-59-1</vn><fn/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="to catch in or as if in a trap; immobilize" type="">
        <commentary>
            Note: Compare to sense 1. This sense only applies to the physical
            properties of a trap.
        </commentary>
        <examples>
            The search-and-rescue teams entered the mine 11 hours after the
            blast trapped the miners.  
            Marc crossed both his blades and trapped Shannon's sword above his head.
            By a clever trick, the children brought down a landslide that
            trapped the serpent. 
            The climber was trapped between the rocks for 5 hours.
        </examples>
        <mappings>
            <gr_sense/>
            <wn version="3.0">2,3,4</wn>
            <wn lemma="" version=""/>
            <omega/>
            <pb>trap.01</pb>
            <vn>pocket-9.10</vn><fn/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="3" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="clarklm" sample_score="-"/>

<ita count="17" ann_1_2_agreement="0.705882352941" />
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/thick-n.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="thick-n">
    <commentary>
        monosemous
    </commentary>
    
    <sense group="1" n="1" name="location of the busiest activity" type="">
        <commentary>
            THICK[+location][+of_activity][+busiest]
        </commentary>
        <examples>
            In the thick of battle it was hard to tell friend from foe.
            Don't bother John while he's in the thick of finals this week.
        </examples>
        <mappings>
            <wn version="3.0">1</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    
    
    <WORD_META authors="ahouston" sample_score="-"/>
</inventory>

=== ksipos/polysemy-assessment/evaluating/baselines/english/ontonotes/sense-inventories/translate-v.xml
<?xml version="1.0" ?><!DOCTYPE inventory  SYSTEM 'inventory.dtd'><inventory lemma="translate-v">    
    <commentary>
    </commentary>
    <sense group="1" n="1" name="render one language in another language" type="">  
        <commentary>
            Includes: Computer language
            Note: Here, the sense only extends to the process of transfering
            something from one language to another. Whether the translation is
            capable of appropriately expressing the original language is beside
            the point. Such expression is handled by the sense 2.  
        </commentary>
        <examples>
            We were asked to translate a list of sentences.
            She works for the EU, translating from English into French.
            How does it translate the program into machine code?
            Occasionally, I translated French and German poems.
        </examples>
        <mappings>
            <wn version="3.0">1,3</wn>   
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="2" name="express or transform in a new form or language" type="">
        <commentary>
        </commentary>
        <examples>
            Here are three poems in English, but no most poetry doesn't translate well.
            The idiom doesn't translate well.
            So how does this theory translate into practical policy?
            Braque translated collage into oil.
            What I held back was too sacred and personal to translate into words.
            Not everything we learned in college translates well to the world of business.
            Today's steady growth in household income translate into more purchasing power.
        </examples>
        <mappings>
            <wn version="3.0">2,6,7</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="3" name="transfer to a place or into a state" type="">
        <commentary>
        </commentary>
        <examples>
            She was translated from her small country home to a high-rise city apartment.
            Oh, the sweetness of being translated into a state of complete purity and perfection!
        </examples>
        <mappings>
            <wn version="3.0">4</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="4" name="say or interpret something in understandable terms" type="">
        <commentary>
        </commentary>
        <examples>
            Can you translate the instructions in this manual for a layman?
            Is there a need to translate the psychiatrist's remarks?
            I translated his silence as approval.
            You'll have to translate the attendant's vague mumbling for us.
        </examples>
        <mappings>
            <wn version="3.0">9</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="5" name="PHYSICS-move a body sideways through space in a stright line without rotation" type="">
        <commentary>
        </commentary>
        <examples>
            Thirdly, the rotated object is translated to the new target position.
            The target is then translated to desired position and orientation.
        </examples>
        <mappings>
            <wn version="3.0">5,8</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
    <sense group="1" n="6" name="BIOLOGY-determine amino acid sequence during a protein synthesis" type="">
        <commentary>
        </commentary>
        <examples>
            This service transcribes DNA into mRNA and translates mRNA into Amino Acid sequences.
            The information carried by the DNA bases translates into proteins.
        </examples>
        <mappings>
            <wn version="3.0">10</wn>
            <omega/>
            <pb/>
        </mappings>
        <SENSE_META clarity=""/>
    </sense>
<sense group="1" n="7" name="none of the above" type="">
  <commentary>
Automatically generated NOTA sense (bbn)
  </commentary>
  <examples>
  </examples>
  <mappings>
    <wn version="2.1"></wn>
    <omega></omega><pb></pb>
    <fn></fn>
  </mappings><SENSE_META clarity=""/>
</sense>
    <WORD_META authors="hwangd" sample_score="-"/>
     

<ita count="38" ann_1_2_agreement="0.763157894737" />
</inventory>
